### ISSUE TITLE
Ubuntu Dependencies

### ISSUE THREAD

**Issue by zyphlar** [kensanata/bitlbee-mastodon#1]
Firstly, `autotools` is apparently called `autoconf` in Ubuntu, so to get around this error:

```
./autogen.sh: 18: ./autogen.sh: autoreconf: not found
```

I had to `apt install autoconf`.

Then to get around this error:

```
configure.ac:32: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:33: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

I had to `apt install libtool`

Just FYI in terms of actual Ubuntu dependencies.

Thanks for the plugin!

**Comment by kensanata** [comment]
Thanks. I added a short note.
