### ISSUE TITLE
Replying to multiple people

### ISSUE THREAD

**Issue by kensanata** [kensanata/bitlbee-mastodon#18]
One of the things that really bothers me about the bitlbee-mastodon plugin is that conversations with multiple participants are tricky. Help says: "The handle of the original author you are replying to will be prepended automatically. It is up to you to mention any of the other people mentioned in the original." The problem is that a. we need to list them and b. we need to use their fully qualified names when they're not on the same instance, and this is usually not visible in the UI. I mean, you can use `info <id>` to get the accounts, but that's overkill. It would be better to have a separate option to the `reply` command, i.e. `reply all 77 foo` or `reply all @bar baz`.

**Comment by kensanata** [comment]
I tried saving all the mentions in out log, but I think this road leads nowhere. If you are replying to older toots, it won't work. Thus, I think the only solution is to make replies a multi-request thing: for every reply, make a request to get the mentions, then post the real reply.

**Comment by Hund** [comment]
Any news about this? It's the one thing I miss with this plugin for Bitlbee. Right now I have to fire up the web browser and reply to them there unless there's a single person I'm replying to.

**Comment by kensanata** [comment]
I’m not implementing it in the foreseeable future, so please have a go at it, if you fell like giving it a try.
