### ISSUE TITLE
Subscribe to local and federated timelines

### ISSUE THREAD

**Issue by rodneyrod** [kensanata/bitlbee-mastodon#2]
Or if these options already exist, reference them in documentation.

**Comment by kensanata** [comment]
Yeah, this is missing at the moment. I think all we have is the TIMELINE command which we could adapt, but all it does is show some toots, not open a new stream. A new stream would be opened like the hashtag subscriptions, except for the two special keywords LOCAL and FEDERATED, I guess.

**Comment by rodneyrod** [comment]
Yep that's pretty much what I had in mind too.

**Comment by kensanata** [comment]
The current commit 9423fb6 has support for the *local* and *federated* keywords when using the *timeline* command. But that's just a display of the last batch. I also implemented joining the channel and all that (see `help mpublic` for more). Surprisingly, it seems that the [streaming API](https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md#endpoints) does not support just local toots. Thus, right now you're getting all the public toots when joining a local channel, i.e. the federated and the local timeline are not distinguished.

**Comment by kensanata** [comment]
I created an [issue](https://github.com/tootsuite/mastodon/issues/5839) for this.

**Comment by kensanata** [comment]
The new URL seems to work, even if it seems a bit slow right now.

**Comment by kensanata** [comment]
Fixed in 180569f.

**Comment by kensanata** [comment]
Hm. I think there's still a bug lurking in there somewhere. When *leaving* the federated or local channel, the HTTP request isn't killed, the statuses still keep coming, and now they just end up in your default timeline.

**Comment by kensanata** [comment]
I *think* this is fixed by b3828c2. I'm still not sure everything works as it should. For example, when I joined both the local and the federated timeline of my instance, I had the impression that statuses on the local timeline got doubled. If that is indeed an issue, we should create a new one for that.

**Comment by rodneyrod** [comment]
Thanks so much for this, and for the extra work that went upstream too.

**Comment by kensanata** [comment]
I think 0452610 fixes the toot duplication in the home stream.
