### ISSUE TITLE
My Mastodon account gets removed and I don't know why

### ISSUE THREAD

**Issue by Hund** [kensanata/bitlbee-mastodon#3]
I installed this plugin a few days ago and I added my Mastodon account and everything was fine for a day or so, until I noticed that I didn't recieve any updates from people. After some quick debugging I noticed that my account was completley gone from Bitlbee. I added it a second time and now about a day or so later, it's gone again.. :|

I have never had this issue before and I'm not sure how to debug it and can't see anything in the logs either.

What do I do?

**Comment by kensanata** [comment]
I think you need to make sure you save your config. Otherwise, all your info is gone when the Bitlbee server restarts. If you saved your config, find the file and make a backup copy. When you run into your problem, compare the file with your backup. Anything suspicious? That’s what I would do.

**Comment by Hund** [comment]
Oh. I see. Thanks! I'll do that. :)

**Comment by Hund** [comment]
It seems like I was the bug here, when I forgot to save the config. :) Thanks for the help!
