### ISSUE TITLE
Join local and public timelines

### ISSUE THREAD

**Issue by fauno** [kensanata/bitlbee-mastodon#31]
I couldn't find this on the docs, is there a way to join the local and public timelines as new channels, besides the home timeline?

**Comment by kensanata** [comment]
I never do it but there is a way: https://github.com/kensanata/bitlbee-mastodon/blob/master/doc/HELP.md
Let me know whether it works for you.

**Comment by fauno** [comment]
Ah thanks, how did I miss that :P
