### ISSUE TITLE
doesn't build on debian (fails to find bitlbee)

### ISSUE THREAD

**Issue by libBletchley** [kensanata/bitlbee-mastodon#5]
This is the output of the `./configure` cmd:
```
..
checking for BITLBEE... no
configure: error: Package requirements (bitlbee >= 3.5) were not met:

No package 'bitlbee' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BITLBEE_CFLAGS
and BITLBEE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Is there an easier way to install this?  Like a deb file, or perhaps a tarball that doesn't need to be built?

**Comment by kensanata** [comment]
There isn't. But I'd be interested in finding somebody who does the
packaging! Can you do it?

When I see your error message, the first thought I have is that you need
the bitlbee-dev
<https://github.com/kensanata/bitlbee-mastodon#build-dependencies> package.
Perhaps you only have bitlbee installed?

**Comment by Cightline** [comment]
I was able to install it, I think @libBletchley needs bitlbee-dev.

**Comment by libBletchley** [comment]
@kensanata 

Sorry i missed your reply somehow.  Indeed installing `bitlbee-dev` solved the problem.

My hasty install technique was to ignore the dependencies (on the off chance that I have them anyway), and then install what's missing as errors arise.  That stung me, because the error message `No package 'bitlbee' found` was erroneous.  I thought: "i do have bitlbee installed, why isn't ./configure finding it?"  The error msg could perhaps be improved.  Anyway, I appreciate the help.

**Comment by kensanata** [comment]
I don't think I can influence the error message: from the point of view of the build system, we depend on bitlbee (see [configure.ac](https://github.com/kensanata/bitlbee-mastodon/blob/master/configure.ac)) and it doesn't know (nor care) that on Debian systems the headers have been split into a separate package. The [dependency section](https://github.com/kensanata/bitlbee-mastodon#build-dependencies) of the README file really is the only point where I can tell people about this.
